/*
Module : ScintillaCtrl.h
Purpose: Defines the interface for an MFC wrapper class for the Scintilla edit control (www.scintilla.org)
Created: PJN / 19-03-2004

Copyright (c) 2004 - 2022 by PJ Naughter (Web: www.naughter.com, Email: pjna@naughter.com)

All rights reserved.

Copyright / Usage Details:

You are allowed to include the source code in any product (commercial, shareware, freeware or otherwise) 
when your product is released in binary form. You are allowed to modify the source code in any way you want 
except you cannot modify the copyright details at the top of each module. If you want to distribute source 
code with your application, then you are only allowed to distribute versions released by the author. This is 
to maintain a single distribution point for the source code.

*/


//////////////////// Macros / Defines /////////////////////////////////////////

#pragma once

#ifndef __SCINTILLACTRL_H__
#define __SCINTILLACTRL_H__

#ifndef SCINTILLA_H
#pragma message("To avoid this message, please put scintilla.h in your pre compiled header (normally stdafx.h)")
#include <Scintilla.h>
#endif //#ifndef SCINTILLA_H

#ifndef SCINTILLACTRL_EXT_CLASS
#define SCINTILLACTRL_EXT_CLASS
#endif //#ifndef SCINTILLACTRL_EXT_CLASS

//////////////////// Classes //////////////////////////////////////////////////

class SCINTILLACTRL_EXT_CLASS CScintillaCtrl : public CWnd
{
protected:
  using CWnd::Create; //To suppress C4263

public:
//Constructors / Destructors
  CScintillaCtrl() noexcept;

//Creation
  BOOL Create(DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, UINT nID, DWORD dwExStyle = 0, LPVOID lpParam = nullptr);

//Misc
  void SetupDirectAccess();

  inline LRESULT Call(_In_ UINT message, _In_ WPARAM wParam, _In_ LPARAM lParam)
  {
    //Validate our parameters
    ASSERT(::IsWindow(m_hWnd)); //Window must be valid

    if (m_bCallDirect)
    {
      ASSERT(m_DirectFunction != nullptr); //Direct function must be valid
      return (m_DirectFunction)(m_DirectPointer, message, wParam, lParam);
    }
    else
      return SendMessage(message, wParam, lParam);
  }

#pragma warning(suppress: 26440)
  inline LRESULT Call(_In_ UINT message, _In_ WPARAM wParam, _In_ LPARAM lParam, _Inout_ int* pStatus)
  {
    //Validate our parameters
    ASSERT(::IsWindow(m_hWnd)); //Window must be valid
    ASSERT(m_DirectStatusFunction != nullptr); //Direct status function must be valid

    return (m_DirectStatusFunction)(m_DirectPointer, message, wParam, lParam, pStatus);
  }

  [[nodiscard]] SciFnDirect GetDirectFunction();
  [[nodiscard]] sptr_t GetDirectPointer();
  [[nodiscard]] BOOL GetCallDirect() const noexcept;
  [[nodiscard]] SciFnDirectStatus GetDirectStatusFunction();
  void SetCallDirect(_In_ BOOL bDirect) noexcept;

//Unicode support
#ifdef _UNICODE
  void AddText(_In_ int length, _In_ const wchar_t* text);
  void InsertText(_In_ Sci_Position pos, _In_z_ const wchar_t* text);
  void ChangeInsertion(_In_ int length, _In_z_ const wchar_t* text);
  [[nodiscard]] CStringW GetSelText();
  [[nodiscard]] CStringW GetCurLine();
  void StyleSetFont(_In_ int style, _In_z_ const wchar_t* fontName);
  void SetWordChars(_In_z_ const wchar_t* characters);
  void AutoCShow(_In_ int lenEntered, _In_z_ const wchar_t* itemList);
  void AutoCStops(_In_z_ const wchar_t* characterSet);
  void AutoCSelect(_In_z_ const wchar_t* text);
  void AutoCSetFillUps(_In_z_ const wchar_t* characterSet);
  void UserListShow(_In_ int listType, _In_z_ const wchar_t* itemList);
  [[nodiscard]] CStringW GetLine(_In_ intptr_t line);
  void ReplaceSel(_In_z_ const wchar_t* text);
  void SetText(_In_z_ const wchar_t* text);
  [[nodiscard]] CStringW GetText(_In_ int length);
  Sci_Position ReplaceTarget(_In_ Sci_Position length, _In_ const wchar_t* text);
  Sci_Position ReplaceTargetRE(_In_ Sci_Position length, _In_ const wchar_t* text);
  Sci_Position SearchInTarget(_In_ Sci_Position length, _In_ const wchar_t* text);
  void CallTipShow(_In_ Sci_Position pos, _In_z_ const wchar_t* definition);
  int TextWidth(_In_ int style, _In_z_ const wchar_t* text);
  void AppendText(_In_ int length, _In_ const wchar_t* text);
  Sci_Position SearchNext(_In_ int flags, _In_z_ const wchar_t* text);
  Sci_Position SearchPrev(_In_ int flags, _In_z_ const wchar_t* text);
  void CopyText(_In_ int length, _In_ const wchar_t* text);
  void SetWhitespaceChars(_In_z_ const wchar_t* characters);
  void SetScintillaProperty(_In_z_ const wchar_t* key, _In_z_ const wchar_t* value);
  void SetKeyWords(_In_ int keywordSet, _In_z_ const wchar_t* keyWords);
  void SetIdentifiers(_In_ int style, _In_z_ const wchar_t* identifiers);
  [[nodiscard]] CStringW GetScintillaProperty(_In_z_ const wchar_t* key);
  [[nodiscard]] CStringW GetPropertyExpanded(_In_z_ const wchar_t* key);
  [[nodiscard]] int GetPropertyInt(_In_z_ const wchar_t* key, _In_ int defaultValue);
  [[nodiscard]] CStringW StyleGetFont(_In_ int style);
  void MarginSetText(_In_ intptr_t line, _In_z_ const wchar_t* text);
  void AnnotationSetText(_In_ intptr_t line, _In_z_ const wchar_t* text);
  [[nodiscard]] CStringW AutoCGetCurrentText();
  [[nodiscard]] CStringW GetLexerLanguage();
  [[nodiscard]] CStringW PropertyNames();
  [[nodiscard]] int PropertyType(_In_z_ const wchar_t* name);
  void ToggleFoldShowText(_In_ intptr_t line, _In_ const wchar_t* text);
  void SetDefaultFoldDisplayText(_In_z_ const wchar_t* text);
  void EOLAnnotationSetText(_In_ intptr_t line, _In_ const wchar_t* text);
  [[nodiscard]] CStringW EOLAnnotationGetText(_In_ intptr_t line);
  [[nodiscard]] CStringW DescribeProperty(_In_z_ const wchar_t* name);
  [[nodiscard]] CStringW DescribeKeyWordSets();
  [[nodiscard]] CStringW GetTag(_In_ int tagNumber);
  [[nodiscard]] CStringW GetWordChars();
  [[nodiscard]] CStringW GetWhitespaceChars();
  [[nodiscard]] CStringW GetPunctuationChars();
  [[nodiscard]] CStringW GetTargetText();
  [[nodiscard]] CStringW NameOfStyle(_In_ int style);
  [[nodiscard]] CStringW TagsOfStyle(_In_ int style);
  [[nodiscard]] CStringW DescriptionOfStyle(_In_ int style);
  [[nodiscard]] CStringW GetDefaultFoldDisplayText();
  [[nodiscard]] CStringW MarginGetText(_In_ intptr_t line);
  [[nodiscard]] CStringW GetFontLocale();
  [[nodiscard]] CStringW MarginGetStyles(_In_ intptr_t line);
  [[nodiscard]] CStringW AnnotationGetText(_In_ intptr_t line);
  [[nodiscard]] CStringW AnnotationGetStyles(_In_ intptr_t line);
  [[nodiscard]] CStringW GetSubStyleBases();

  [[nodiscard]] static CStringW UTF82W(_In_NLS_string_(nLength) const char* pszText, _In_ int nLength);
  [[nodiscard]] static CStringA W2UTF8(_In_NLS_string_(nLength) const wchar_t* pszText, _In_ int nLength);
#else
  [[nodiscard]] CStringA GetSelText();
  [[nodiscard]] CStringA GetCurLine();
  [[nodiscard]] CStringA GetLine(_In_ intptr_t line);
  [[nodiscard]] CStringA GetScintillaProperty(_In_z_ const char* key);
  [[nodiscard]] CStringA GetText(_In_ int length);
  [[nodiscard]] CStringA GetPropertyExpanded(_In_z_ const char* key);
  [[nodiscard]] CStringA StyleGetFont(_In_ int style);
  [[nodiscard]] CStringA AutoCGetCurrentText();
  [[nodiscard]] CStringA GetLexerLanguage();
  [[nodiscard]] CStringA PropertyNames();
  [[nodiscard]] CStringA EOLAnnotationGetText(_In_ intptr_t line);
  [[nodiscard]] CStringA DescribeProperty(_In_z_ const char* name);
  [[nodiscard]] CStringA DescribeKeyWordSets();
  [[nodiscard]] CStringA GetTag(_In_ int tagNumber);
  [[nodiscard]] CStringA GetWordChars();
  [[nodiscard]] CStringA GetWhitespaceChars();
  [[nodiscard]] CStringA GetPunctuationChars();
  [[nodiscard]] CStringA GetTargetText();
  [[nodiscard]] CStringA NameOfStyle(_In_ int style);
  [[nodiscard]] CStringA TagsOfStyle(_In_ int style);
  [[nodiscard]] CStringA DescriptionOfStyle(_In_ int style);
  [[nodiscard]] CStringA GetDefaultFoldDisplayText();
  [[nodiscard]] CStringA MarginGetText(_In_ intptr_t line);
  [[nodiscard]] CStringA GetFontLocale();
  [[nodiscard]] CStringA MarginGetStyles(_In_ intptr_t line);
  [[nodiscard]] CStringA AnnotationGetText(_In_ intptr_t line);
  [[nodiscard]] CStringA AnnotationGetStyles(_In_ intptr_t line);
  [[nodiscard]] CStringA GetSubStyleBases();
#endif //#ifdef _UNICODE

//Auto generated using the "ConvertScintillaiface.js" script
  void AddText(_In_ Sci_Position length, _In_reads_bytes_(length) const char* text);
  void AddStyledText(_In_ Sci_Position length, _In_reads_bytes_(length) char* c);
  void InsertText(_In_ Sci_Position pos, _In_z_ const char* text);
  void ChangeInsertion(_In_ Sci_Position length, _In_reads_bytes_(length) const char* text);
  void ClearAll();
  void DeleteRange(_In_ Sci_Position start, _In_ Sci_Position lengthDelete);
  void ClearDocumentStyle();
  [[nodiscard]] Sci_Position GetLength();
  [[nodiscard]] int GetCharAt(_In_ Sci_Position pos);
  [[nodiscard]] Sci_Position GetCurrentPos();
  [[nodiscard]] Sci_Position GetAnchor();
  [[nodiscard]] int GetStyleAt(_In_ Sci_Position pos);
  [[nodiscard]] int GetStyleIndexAt(_In_ Sci_Position pos);
  void Redo();
  void SetUndoCollection(_In_ BOOL collectUndo);
  void SelectAll();
  void SetSavePoint();
  Sci_Position GetStyledText(_Inout_ Sci_TextRange* tr);
  BOOL CanRedo();
  [[nodiscard]] intptr_t MarkerLineFromHandle(_In_ int markerHandle);
  void MarkerDeleteHandle(_In_ int markerHandle);
  [[nodiscard]] int MarkerHandleFromLine(_In_ intptr_t line, _In_ int which);
  [[nodiscard]] int MarkerNumberFromLine(_In_ intptr_t line, _In_ int which);
  [[nodiscard]] BOOL GetUndoCollection();
  [[nodiscard]] int GetViewWS();
  void SetViewWS(_In_ int viewWS);
  [[nodiscard]] int GetTabDrawMode();
  void SetTabDrawMode(_In_ int tabDrawMode);
  [[nodiscard]] Sci_Position PositionFromPoint(_In_ int x, _In_ int y);
  [[nodiscard]] Sci_Position PositionFromPointClose(_In_ int x, _In_ int y);
  void GotoLine(_In_ intptr_t line);
  void GotoPos(_In_ Sci_Position caret);
  void SetAnchor(_In_ Sci_Position anchor);
  Sci_Position GetCurLine(_In_ Sci_Position length, _Inout_opt_z_ char* text);
  [[nodiscard]] Sci_Position GetEndStyled();
  void ConvertEOLs(_In_ int eolMode);
  [[nodiscard]] int GetEOLMode();
  void SetEOLMode(_In_ int eolMode);
  void StartStyling(_In_ Sci_Position start, _In_ int unused);
  void SetStyling(_In_ Sci_Position length, _In_ int style);
  [[nodiscard]] BOOL GetBufferedDraw();
  void SetBufferedDraw(_In_ BOOL buffered);
  void SetTabWidth(_In_ int tabWidth);
  [[nodiscard]] int GetTabWidth();
  void SetTabMinimumWidth(_In_ int pixels);
  [[nodiscard]] int GetTabMinimumWidth();
  void ClearTabStops(_In_ intptr_t line);
  void AddTabStop(_In_ intptr_t line, _In_ int x);
  [[nodiscard]] int GetNextTabStop(_In_ intptr_t line, _In_ int x);
  void SetCodePage(_In_ int codePage);
  void SetFontLocale(_In_z_ const char* localeName);
  int GetFontLocale(_Inout_opt_z_ char* localeName);
  [[nodiscard]] int GetIMEInteraction();
  void SetIMEInteraction(_In_ int imeInteraction);
  void MarkerDefine(_In_ int markerNumber, _In_ int markerSymbol);
  void MarkerSetFore(_In_ int markerNumber, _In_ COLORREF fore);
  void MarkerSetBack(_In_ int markerNumber, _In_ COLORREF back);
  void MarkerSetBackSelected(_In_ int markerNumber, _In_ COLORREF back);
  void MarkerSetForeTranslucent(_In_ int markerNumber, _In_ int fore);
  void MarkerSetBackTranslucent(_In_ int markerNumber, _In_ int back);
  void MarkerSetBackSelectedTranslucent(_In_ int markerNumber, _In_ int back);
  void MarkerSetStrokeWidth(_In_ int markerNumber, _In_ int hundredths);
  void MarkerEnableHighlight(_In_ BOOL enabled);
  int MarkerAdd(_In_ intptr_t line, _In_ int markerNumber);
  void MarkerDelete(_In_ intptr_t line, _In_ int markerNumber);
  void MarkerDeleteAll(_In_ int markerNumber);
  [[nodiscard]] int MarkerGet(_In_ intptr_t line);
  [[nodiscard]] intptr_t MarkerNext(_In_ intptr_t lineStart, _In_ int markerMask);
  [[nodiscard]] intptr_t MarkerPrevious(_In_ intptr_t lineStart, _In_ int markerMask);
  void MarkerDefinePixmap(_In_ int markerNumber, _In_ const char* pixmap);
  void MarkerAddSet(_In_ intptr_t line, _In_ int markerSet);
  void MarkerSetAlpha(_In_ int markerNumber, _In_ int alpha);
  [[nodiscard]] int MarkerGetLayer(_In_ int markerNumber);
  void MarkerSetLayer(_In_ int markerNumber, _In_ int layer);
  void SetMarginTypeN(_In_ int margin, _In_ int marginType);
  [[nodiscard]] int GetMarginTypeN(_In_ int margin);
  void SetMarginWidthN(_In_ int margin, _In_ int pixelWidth);
  [[nodiscard]] int GetMarginWidthN(_In_ int margin);
  void SetMarginMaskN(_In_ int margin, _In_ int mask);
  [[nodiscard]] int GetMarginMaskN(_In_ int margin);
  void SetMarginSensitiveN(_In_ int margin, _In_ BOOL sensitive);
  [[nodiscard]] BOOL GetMarginSensitiveN(_In_ int margin);
  void SetMarginCursorN(_In_ int margin, _In_ int cursor);
  [[nodiscard]] int GetMarginCursorN(_In_ int margin);
  void SetMarginBackN(_In_ int margin, _In_ COLORREF back);
  [[nodiscard]] COLORREF GetMarginBackN(_In_ int margin);
  void SetMargins(_In_ int margins);
  [[nodiscard]] int GetMargins();
  void StyleClearAll();
  void StyleSetFore(_In_ int style, _In_ COLORREF fore);
  void StyleSetBack(_In_ int style, _In_ COLORREF back);
  void StyleSetBold(_In_ int style, _In_ BOOL bold);
  void StyleSetItalic(_In_ int style, _In_ BOOL italic);
  void StyleSetSize(_In_ int style, _In_ int sizePoints);
  void StyleSetFont(_In_ int style, _In_z_ const char* fontName);
  void StyleSetEOLFilled(_In_ int style, _In_ BOOL eolFilled);
  void StyleResetDefault();
  void StyleSetUnderline(_In_ int style, _In_ BOOL underline);
  [[nodiscard]] COLORREF StyleGetFore(_In_ int style);
  [[nodiscard]] COLORREF StyleGetBack(_In_ int style);
  [[nodiscard]] BOOL StyleGetBold(_In_ int style);
  [[nodiscard]] BOOL StyleGetItalic(_In_ int style);
  [[nodiscard]] int StyleGetSize(_In_ int style);
  int StyleGetFont(_In_ int style, _Inout_opt_z_ char* fontName);
  [[nodiscard]] BOOL StyleGetEOLFilled(_In_ int style);
  [[nodiscard]] BOOL StyleGetUnderline(_In_ int style);
  [[nodiscard]] int StyleGetCase(_In_ int style);
  [[nodiscard]] int StyleGetCharacterSet(_In_ int style);
  [[nodiscard]] BOOL StyleGetVisible(_In_ int style);
  [[nodiscard]] BOOL StyleGetChangeable(_In_ int style);
  [[nodiscard]] BOOL StyleGetHotSpot(_In_ int style);
  void StyleSetCase(_In_ int style, _In_ int caseVisible);
  void StyleSetSizeFractional(_In_ int style, _In_ int sizeHundredthPoints);
  [[nodiscard]] int StyleGetSizeFractional(_In_ int style);
  void StyleSetWeight(_In_ int style, _In_ int weight);
  [[nodiscard]] int StyleGetWeight(_In_ int style);
  void StyleSetCharacterSet(_In_ int style, _In_ int characterSet);
  void StyleSetHotSpot(_In_ int style, _In_ BOOL hotspot);
  void StyleSetCheckMonospaced(_In_ int style, _In_ BOOL checkMonospaced);
  [[nodiscard]] BOOL StyleGetCheckMonospaced(_In_ int style);
  void SetElementColour(_In_ int element, _In_ int colourElement);
  [[nodiscard]] int GetElementColour(_In_ int element);
  void ResetElementColour(_In_ int element);
  [[nodiscard]] BOOL GetElementIsSet(_In_ int element);
  [[nodiscard]] BOOL GetElementAllowsTranslucent(_In_ int element);
  [[nodiscard]] int GetElementBaseColour(_In_ int element);
  void SetSelFore(_In_ BOOL useSetting, _In_ COLORREF fore);
  void SetSelBack(_In_ BOOL useSetting, _In_ COLORREF back);
  [[nodiscard]] int GetSelAlpha();
  void SetSelAlpha(_In_ int alpha);
  [[nodiscard]] BOOL GetSelEOLFilled();
  void SetSelEOLFilled(_In_ BOOL filled);
  [[nodiscard]] int GetSelectionLayer();
  void SetSelectionLayer(_In_ int layer);
  [[nodiscard]] int GetCaretLineLayer();
  void SetCaretLineLayer(_In_ int layer);
  [[nodiscard]] BOOL GetCaretLineHighlightSubLine();
  void SetCaretLineHighlightSubLine(_In_ BOOL subLine);
  void SetCaretFore(_In_ COLORREF fore);
  void AssignCmdKey(_In_ DWORD keyDefinition, _In_ int sciCommand);
  void ClearCmdKey(_In_ DWORD keyDefinition);
  void ClearAllCmdKeys();
  void SetStylingEx(_In_ Sci_Position length, _In_ const char* styles);
  void StyleSetVisible(_In_ int style, _In_ BOOL visible);
  [[nodiscard]] int GetCaretPeriod();
  void SetCaretPeriod(_In_ int periodMilliseconds);
  void SetWordChars(_In_ const char* characters);
  int GetWordChars(_Inout_opt_z_ char* characters);
  void SetCharacterCategoryOptimization(_In_ int countCharacters);
  [[nodiscard]] int GetCharacterCategoryOptimization();
  void BeginUndoAction();
  void EndUndoAction();
  void IndicSetStyle(_In_ int indicator, _In_ int indicatorStyle);
  [[nodiscard]] int IndicGetStyle(_In_ int indicator);
  void IndicSetFore(_In_ int indicator, _In_ COLORREF fore);
  [[nodiscard]] COLORREF IndicGetFore(_In_ int indicator);
  void IndicSetUnder(_In_ int indicator, _In_ BOOL under);
  [[nodiscard]] BOOL IndicGetUnder(_In_ int indicator);
  void IndicSetHoverStyle(_In_ int indicator, _In_ int indicatorStyle);
  [[nodiscard]] int IndicGetHoverStyle(_In_ int indicator);
  void IndicSetHoverFore(_In_ int indicator, _In_ COLORREF fore);
  [[nodiscard]] COLORREF IndicGetHoverFore(_In_ int indicator);
  void IndicSetFlags(_In_ int indicator, _In_ int flags);
  [[nodiscard]] int IndicGetFlags(_In_ int indicator);
  void IndicSetStrokeWidth(_In_ int indicator, _In_ int hundredths);
  [[nodiscard]] int IndicGetStrokeWidth(_In_ int indicator);
  void SetWhitespaceFore(_In_ BOOL useSetting, _In_ COLORREF fore);
  void SetWhitespaceBack(_In_ BOOL useSetting, _In_ COLORREF back);
  void SetWhitespaceSize(_In_ int size);
  [[nodiscard]] int GetWhitespaceSize();
  void SetLineState(_In_ intptr_t line, _In_ int state);
  [[nodiscard]] int GetLineState(_In_ intptr_t line);
  [[nodiscard]] int GetMaxLineState();
  [[nodiscard]] BOOL GetCaretLineVisible();
  void SetCaretLineVisible(_In_ BOOL show);
  [[nodiscard]] COLORREF GetCaretLineBack();
  void SetCaretLineBack(_In_ COLORREF back);
  [[nodiscard]] int GetCaretLineFrame();
  void SetCaretLineFrame(_In_ int width);
  void StyleSetChangeable(_In_ int style, _In_ BOOL changeable);
  void AutoCShow(_In_ Sci_Position lengthEntered, _In_z_ const char* itemList);
  void AutoCCancel();
  [[nodiscard]] BOOL AutoCActive();
  [[nodiscard]] Sci_Position AutoCPosStart();
  void AutoCComplete();
  void AutoCStops(_In_z_ const char* characterSet);
  void AutoCSetSeparator(_In_ int separatorCharacter);
  [[nodiscard]] int AutoCGetSeparator();
  void AutoCSelect(_In_z_ const char* select);
  void AutoCSetCancelAtStart(_In_ BOOL cancel);
  [[nodiscard]] BOOL AutoCGetCancelAtStart();
  void AutoCSetFillUps(_In_z_ const char* characterSet);
  void AutoCSetChooseSingle(_In_ BOOL chooseSingle);
  [[nodiscard]] BOOL AutoCGetChooseSingle();
  void AutoCSetIgnoreCase(_In_ BOOL ignoreCase);
  [[nodiscard]] BOOL AutoCGetIgnoreCase();
  void UserListShow(_In_ int listType, _In_z_ const char* itemList);
  void AutoCSetAutoHide(_In_ BOOL autoHide);
  [[nodiscard]] BOOL AutoCGetAutoHide();
  void AutoCSetOptions(_In_ int options);
  [[nodiscard]] int AutoCGetOptions();
  void AutoCSetDropRestOfWord(_In_ BOOL dropRestOfWord);
  [[nodiscard]] BOOL AutoCGetDropRestOfWord();
  void RegisterImage(_In_ int type, _In_ const char* xpmData);
  void ClearRegisteredImages();
  [[nodiscard]] int AutoCGetTypeSeparator();
  void AutoCSetTypeSeparator(_In_ int separatorCharacter);
  void AutoCSetMaxWidth(_In_ int characterCount);
  [[nodiscard]] int AutoCGetMaxWidth();
  void AutoCSetMaxHeight(_In_ int rowCount);
  [[nodiscard]] int AutoCGetMaxHeight();
  void SetIndent(_In_ int indentSize);
  [[nodiscard]] int GetIndent();
  void SetUseTabs(_In_ BOOL useTabs);
  [[nodiscard]] BOOL GetUseTabs();
  void SetLineIndentation(_In_ intptr_t line, _In_ int indentation);
  [[nodiscard]] int GetLineIndentation(_In_ intptr_t line);
  [[nodiscard]] Sci_Position GetLineIndentPosition(_In_ intptr_t line);
  [[nodiscard]] Sci_Position GetColumn(_In_ Sci_Position pos);
  [[nodiscard]] Sci_Position CountCharacters(_In_ Sci_Position start, _In_ Sci_Position end);
  [[nodiscard]] Sci_Position CountCodeUnits(_In_ Sci_Position start, _In_ Sci_Position end);
  void SetHScrollBar(_In_ BOOL visible);
  [[nodiscard]] BOOL GetHScrollBar();
  void SetIndentationGuides(_In_ int indentView);
  [[nodiscard]] int GetIndentationGuides();
  void SetHighlightGuide(_In_ Sci_Position column);
  [[nodiscard]] Sci_Position GetHighlightGuide();
  [[nodiscard]] Sci_Position GetLineEndPosition(_In_ intptr_t line);
  [[nodiscard]] int GetCodePage();
  [[nodiscard]] COLORREF GetCaretFore();
  [[nodiscard]] BOOL GetReadOnly();
  void SetCurrentPos(_In_ Sci_Position caret);
  void SetSelectionStart(_In_ Sci_Position anchor);
  [[nodiscard]] Sci_Position GetSelectionStart();
  void SetSelectionEnd(_In_ Sci_Position caret);
  [[nodiscard]] Sci_Position GetSelectionEnd();
  void SetEmptySelection(_In_ Sci_Position caret);
  void SetPrintMagnification(_In_ int magnification);
  [[nodiscard]] int GetPrintMagnification();
  void SetPrintColourMode(_In_ int mode);
  [[nodiscard]] int GetPrintColourMode();
  [[nodiscard]] Sci_Position FindText(_In_ int searchFlags, _Inout_ Sci_TextToFind* ft);
  [[nodiscard]] Sci_Position FindTextFull(_In_ int searchFlags, _Inout_ Sci_TextToFindFull* ft);
  [[nodiscard]] Sci_Position FormatRange(_In_ BOOL draw, _In_ Sci_RangeToFormat* fr);
  [[nodiscard]] Sci_Position FormatRangeFull(_In_ BOOL draw, _In_ Sci_RangeToFormatFull* fr);
  [[nodiscard]] intptr_t GetFirstVisibleLine();
  Sci_Position GetLine(_In_ intptr_t line, _Inout_opt_z_ char* text);
  [[nodiscard]] intptr_t GetLineCount();
  void AllocateLines(_In_ intptr_t lines);
  void SetMarginLeft(_In_ int pixelWidth);
  [[nodiscard]] int GetMarginLeft();
  void SetMarginRight(_In_ int pixelWidth);
  [[nodiscard]] int GetMarginRight();
  [[nodiscard]] BOOL GetModify();
  void SetSel(_In_ Sci_Position anchor, _In_ Sci_Position caret);
  Sci_Position GetSelText(_Inout_opt_z_ char* text);
  Sci_Position GetTextRange(_Inout_ Sci_TextRange* tr);
  Sci_Position GetTextRangeFull(_Inout_ Sci_TextRangeFull* tr);
  void HideSelection(_In_ BOOL hide);
  [[nodiscard]] int PointXFromPosition(_In_ Sci_Position pos);
  [[nodiscard]] int PointYFromPosition(_In_ Sci_Position pos);
  [[nodiscard]] intptr_t LineFromPosition(_In_ Sci_Position pos);
  [[nodiscard]] Sci_Position PositionFromLine(_In_ intptr_t line);
  void LineScroll(_In_ Sci_Position columns, _In_ intptr_t lines);
  void ScrollCaret();
  void ScrollRange(_In_ Sci_Position secondary, _In_ Sci_Position primary);
  void ReplaceSel(_In_z_ const char* text);
  void SetReadOnly(_In_ BOOL readOnly);
  void Null();
  [[nodiscard]] BOOL CanPaste();
  [[nodiscard]] BOOL CanUndo();
  void EmptyUndoBuffer();
  void Undo();
  void Cut();
  void Copy();
  void Paste();
  void Clear();
  void SetText(_In_z_ const char* text);
  Sci_Position GetText(_In_ Sci_Position length, _Inout_updates_opt_(length+1) char* text);
  [[nodiscard]] Sci_Position GetTextLength();
  void SetOvertype(_In_ BOOL overType);
  [[nodiscard]] BOOL GetOvertype();
  void SetCaretWidth(_In_ int pixelWidth);
  [[nodiscard]] int GetCaretWidth();
  void SetTargetStart(_In_ Sci_Position start);
  [[nodiscard]] Sci_Position GetTargetStart();
  void SetTargetStartVirtualSpace(_In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetTargetStartVirtualSpace();
  void SetTargetEnd(_In_ Sci_Position end);
  [[nodiscard]] Sci_Position GetTargetEnd();
  void SetTargetEndVirtualSpace(_In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetTargetEndVirtualSpace();
  void SetTargetRange(_In_ Sci_Position start, _In_ Sci_Position end);
  Sci_Position GetTargetText(_Inout_opt_z_ char* text);
  void TargetFromSelection();
  void TargetWholeDocument();
  Sci_Position ReplaceTarget(_In_ Sci_Position length, _In_ const char* text);
  Sci_Position ReplaceTargetRE(_In_ Sci_Position length, _In_ const char* text);
  Sci_Position SearchInTarget(_In_ Sci_Position length, _In_reads_bytes_(length) const char* text);
  void SetSearchFlags(_In_ int searchFlags);
  [[nodiscard]] int GetSearchFlags();
  void CallTipShow(_In_ Sci_Position pos, _In_z_ const char* definition);
  void CallTipCancel();
  [[nodiscard]] BOOL CallTipActive();
  [[nodiscard]] Sci_Position CallTipPosStart();
  void CallTipSetPosStart(_In_ Sci_Position posStart);
  void CallTipSetHlt(_In_ Sci_Position highlightStart, _In_ Sci_Position highlightEnd);
  void CallTipSetBack(_In_ COLORREF back);
  void CallTipSetFore(_In_ COLORREF fore);
  void CallTipSetForeHlt(_In_ COLORREF fore);
  void CallTipUseStyle(_In_ int tabSize);
  void CallTipSetPosition(_In_ BOOL above);
  [[nodiscard]] intptr_t VisibleFromDocLine(_In_ intptr_t docLine);
  [[nodiscard]] intptr_t DocLineFromVisible(_In_ intptr_t displayLine);
  [[nodiscard]] intptr_t WrapCount(_In_ intptr_t docLine);
  void SetFoldLevel(_In_ intptr_t line, _In_ int level);
  [[nodiscard]] int GetFoldLevel(_In_ intptr_t line);
  [[nodiscard]] intptr_t GetLastChild(_In_ intptr_t line, _In_ int level);
  [[nodiscard]] intptr_t GetFoldParent(_In_ intptr_t line);
  void ShowLines(_In_ intptr_t lineStart, _In_ intptr_t lineEnd);
  void HideLines(_In_ intptr_t lineStart, _In_ intptr_t lineEnd);
  [[nodiscard]] BOOL GetLineVisible(_In_ intptr_t line);
  [[nodiscard]] BOOL GetAllLinesVisible();
  void SetFoldExpanded(_In_ intptr_t line, _In_ BOOL expanded);
  [[nodiscard]] BOOL GetFoldExpanded(_In_ intptr_t line);
  void ToggleFold(_In_ intptr_t line);
  void ToggleFoldShowText(_In_ intptr_t line, _In_ const char* text);
  void FoldDisplayTextSetStyle(_In_ int style);
  [[nodiscard]] int FoldDisplayTextGetStyle();
  void SetDefaultFoldDisplayText(_In_z_ const char* text);
  int GetDefaultFoldDisplayText(_Inout_opt_z_ char* text);
  void FoldLine(_In_ intptr_t line, _In_ int action);
  void FoldChildren(_In_ intptr_t line, _In_ int action);
  void ExpandChildren(_In_ intptr_t line, _In_ int level);
  void FoldAll(_In_ int action);
  void EnsureVisible(_In_ intptr_t line);
  void SetAutomaticFold(_In_ int automaticFold);
  [[nodiscard]] int GetAutomaticFold();
  void SetFoldFlags(_In_ int flags);
  void EnsureVisibleEnforcePolicy(_In_ intptr_t line);
  void SetTabIndents(_In_ BOOL tabIndents);
  [[nodiscard]] BOOL GetTabIndents();
  void SetBackSpaceUnIndents(_In_ BOOL bsUnIndents);
  [[nodiscard]] BOOL GetBackSpaceUnIndents();
  void SetMouseDwellTime(_In_ int periodMilliseconds);
  [[nodiscard]] int GetMouseDwellTime();
  [[nodiscard]] Sci_Position WordStartPosition(_In_ Sci_Position pos, _In_ BOOL onlyWordCharacters);
  [[nodiscard]] Sci_Position WordEndPosition(_In_ Sci_Position pos, _In_ BOOL onlyWordCharacters);
  [[nodiscard]] BOOL IsRangeWord(_In_ Sci_Position start, _In_ Sci_Position end);
  void SetIdleStyling(_In_ int idleStyling);
  [[nodiscard]] int GetIdleStyling();
  void SetWrapMode(_In_ int wrapMode);
  [[nodiscard]] int GetWrapMode();
  void SetWrapVisualFlags(_In_ int wrapVisualFlags);
  [[nodiscard]] int GetWrapVisualFlags();
  void SetWrapVisualFlagsLocation(_In_ int wrapVisualFlagsLocation);
  [[nodiscard]] int GetWrapVisualFlagsLocation();
  void SetWrapStartIndent(_In_ int indent);
  [[nodiscard]] int GetWrapStartIndent();
  void SetWrapIndentMode(_In_ int wrapIndentMode);
  [[nodiscard]] int GetWrapIndentMode();
  void SetLayoutCache(_In_ int cacheMode);
  [[nodiscard]] int GetLayoutCache();
  void SetScrollWidth(_In_ int pixelWidth);
  [[nodiscard]] int GetScrollWidth();
  void SetScrollWidthTracking(_In_ BOOL tracking);
  [[nodiscard]] BOOL GetScrollWidthTracking();
  [[nodiscard]] int TextWidth(_In_ int style, _In_z_ const char* text);
  void SetEndAtLastLine(_In_ BOOL endAtLastLine);
  [[nodiscard]] BOOL GetEndAtLastLine();
  [[nodiscard]] int TextHeight(_In_ intptr_t line);
  void SetVScrollBar(_In_ BOOL visible);
  [[nodiscard]] BOOL GetVScrollBar();
  void AppendText(_In_ Sci_Position length, _In_reads_bytes_(length) const char* text);
  [[nodiscard]] int GetPhasesDraw();
  void SetPhasesDraw(_In_ int phases);
  void SetFontQuality(_In_ int fontQuality);
  [[nodiscard]] int GetFontQuality();
  void SetFirstVisibleLine(_In_ intptr_t displayLine);
  void SetMultiPaste(_In_ int multiPaste);
  [[nodiscard]] int GetMultiPaste();
  int GetTag(_In_ int tagNumber, _Inout_opt_z_ char* tagValue);
  void LinesJoin();
  void LinesSplit(_In_ int pixelWidth);
  void SetFoldMarginColour(_In_ BOOL useSetting, _In_ COLORREF back);
  void SetFoldMarginHiColour(_In_ BOOL useSetting, _In_ COLORREF fore);
  void SetAccessibility(_In_ int accessibility);
  [[nodiscard]] int GetAccessibility();
  void LineDown();
  void LineDownExtend();
  void LineUp();
  void LineUpExtend();
  void CharLeft();
  void CharLeftExtend();
  void CharRight();
  void CharRightExtend();
  void WordLeft();
  void WordLeftExtend();
  void WordRight();
  void WordRightExtend();
  void Home();
  void HomeExtend();
  void LineEnd();
  void LineEndExtend();
  void DocumentStart();
  void DocumentStartExtend();
  void DocumentEnd();
  void DocumentEndExtend();
  void PageUp();
  void PageUpExtend();
  void PageDown();
  void PageDownExtend();
  void EditToggleOvertype();
  void Cancel();
  void DeleteBack();
  void Tab();
  void BackTab();
  void NewLine();
  void FormFeed();
  void VCHome();
  void VCHomeExtend();
  void ZoomIn();
  void ZoomOut();
  void DelWordLeft();
  void DelWordRight();
  void DelWordRightEnd();
  void LineCut();
  void LineDelete();
  void LineTranspose();
  void LineReverse();
  void LineDuplicate();
  void LowerCase();
  void UpperCase();
  void LineScrollDown();
  void LineScrollUp();
  void DeleteBackNotLine();
  void HomeDisplay();
  void HomeDisplayExtend();
  void LineEndDisplay();
  void LineEndDisplayExtend();
  void HomeWrap();
  void HomeWrapExtend();
  void LineEndWrap();
  void LineEndWrapExtend();
  void VCHomeWrap();
  void VCHomeWrapExtend();
  void LineCopy();
  void MoveCaretInsideView();
  [[nodiscard]] Sci_Position LineLength(_In_ intptr_t line);
  void BraceHighlight(_In_ Sci_Position posA, _In_ Sci_Position posB);
  void BraceHighlightIndicator(_In_ BOOL useSetting, _In_ int indicator);
  void BraceBadLight(_In_ Sci_Position pos);
  void BraceBadLightIndicator(_In_ BOOL useSetting, _In_ int indicator);
  [[nodiscard]] Sci_Position BraceMatch(_In_ Sci_Position pos, _In_ int maxReStyle);
  [[nodiscard]] Sci_Position BraceMatchNext(_In_ Sci_Position pos, _In_ Sci_Position startPos);
  [[nodiscard]] BOOL GetViewEOL();
  void SetViewEOL(_In_ BOOL visible);
  [[nodiscard]] void* GetDocPointer();
  void SetDocPointer(_In_opt_ void* doc);
  void SetModEventMask(_In_ int eventMask);
  [[nodiscard]] Sci_Position GetEdgeColumn();
  void SetEdgeColumn(_In_ Sci_Position column);
  [[nodiscard]] int GetEdgeMode();
  void SetEdgeMode(_In_ int edgeMode);
  [[nodiscard]] COLORREF GetEdgeColour();
  void SetEdgeColour(_In_ COLORREF edgeColour);
  void MultiEdgeAddLine(_In_ Sci_Position column, _In_ COLORREF edgeColour);
  void MultiEdgeClearAll();
  [[nodiscard]] Sci_Position GetMultiEdgeColumn(_In_ int which);
  void SearchAnchor();
  [[nodiscard]] Sci_Position SearchNext(_In_ int searchFlags, _In_z_ const char* text);
  [[nodiscard]] Sci_Position SearchPrev(_In_ int searchFlags, _In_z_ const char* text);
  [[nodiscard]] intptr_t LinesOnScreen();
  void UsePopUp(_In_ int popUpMode);
  [[nodiscard]] BOOL SelectionIsRectangle();
  void SetZoom(_In_ int zoomInPoints);
  [[nodiscard]] int GetZoom();
  [[nodiscard]] void* CreateDocument(_In_ Sci_Position bytes, _In_ int documentOptions);
  void AddRefDocument(_In_ void* doc);
  void ReleaseDocument(_In_ void* doc);
  [[nodiscard]] int GetDocumentOptions();
  [[nodiscard]] int GetModEventMask();
  void SetCommandEvents(_In_ BOOL commandEvents);
  [[nodiscard]] BOOL GetCommandEvents();
  void SCISetFocus(_In_ BOOL focus);
  [[nodiscard]] BOOL GetFocus();
  void SetStatus(_In_ int status);
  [[nodiscard]] int GetStatus();
  void SetMouseDownCaptures(_In_ BOOL captures);
  [[nodiscard]] BOOL GetMouseDownCaptures();
  void SetMouseWheelCaptures(_In_ BOOL captures);
  [[nodiscard]] BOOL GetMouseWheelCaptures();
  void SetCursor(_In_ int cursorType);
  [[nodiscard]] int GetCursor();
  void SetControlCharSymbol(_In_ int symbol);
  [[nodiscard]] int GetControlCharSymbol();
  void WordPartLeft();
  void WordPartLeftExtend();
  void WordPartRight();
  void WordPartRightExtend();
  void SetVisiblePolicy(_In_ int visiblePolicy, _In_ int visibleSlop);
  void DelLineLeft();
  void DelLineRight();
  void SetXOffset(_In_ int xOffset);
  [[nodiscard]] int GetXOffset();
  void ChooseCaretX();
  void GrabFocus();
  void SetXCaretPolicy(_In_ int caretPolicy, _In_ int caretSlop);
  void SetYCaretPolicy(_In_ int caretPolicy, _In_ int caretSlop);
  void SetPrintWrapMode(_In_ int wrapMode);
  [[nodiscard]] int GetPrintWrapMode();
  void SetHotspotActiveFore(_In_ BOOL useSetting, _In_ COLORREF fore);
  [[nodiscard]] COLORREF GetHotspotActiveFore();
  void SetHotspotActiveBack(_In_ BOOL useSetting, _In_ COLORREF back);
  [[nodiscard]] COLORREF GetHotspotActiveBack();
  void SetHotspotActiveUnderline(_In_ BOOL underline);
  [[nodiscard]] BOOL GetHotspotActiveUnderline();
  void SetHotspotSingleLine(_In_ BOOL singleLine);
  [[nodiscard]] BOOL GetHotspotSingleLine();
  void ParaDown();
  void ParaDownExtend();
  void ParaUp();
  void ParaUpExtend();
  [[nodiscard]] Sci_Position PositionBefore(_In_ Sci_Position pos);
  [[nodiscard]] Sci_Position PositionAfter(_In_ Sci_Position pos);
  [[nodiscard]] Sci_Position PositionRelative(_In_ Sci_Position pos, _In_ Sci_Position relative);
  [[nodiscard]] Sci_Position PositionRelativeCodeUnits(_In_ Sci_Position pos, _In_ Sci_Position relative);
  void CopyRange(_In_ Sci_Position start, _In_ Sci_Position end);
  void CopyText(_In_ Sci_Position length, _In_reads_bytes_(length) const char* text);
  void SetSelectionMode(_In_ int selectionMode);
  [[nodiscard]] int GetSelectionMode();
  [[nodiscard]] BOOL GetMoveExtendsSelection();
  [[nodiscard]] Sci_Position GetLineSelStartPosition(_In_ intptr_t line);
  [[nodiscard]] Sci_Position GetLineSelEndPosition(_In_ intptr_t line);
  void LineDownRectExtend();
  void LineUpRectExtend();
  void CharLeftRectExtend();
  void CharRightRectExtend();
  void HomeRectExtend();
  void VCHomeRectExtend();
  void LineEndRectExtend();
  void PageUpRectExtend();
  void PageDownRectExtend();
  void StutteredPageUp();
  void StutteredPageUpExtend();
  void StutteredPageDown();
  void StutteredPageDownExtend();
  void WordLeftEnd();
  void WordLeftEndExtend();
  void WordRightEnd();
  void WordRightEndExtend();
  void SetWhitespaceChars(_In_z_ const char* characters);
  int GetWhitespaceChars(_Inout_opt_z_ char* characters);
  void SetPunctuationChars(_In_z_ const char* characters);
  int GetPunctuationChars(_Inout_opt_z_ char* characters);
  void SetCharsDefault();
  [[nodiscard]] int AutoCGetCurrent();
  int AutoCGetCurrentText(_Inout_opt_z_ char* text);
  void AutoCSetCaseInsensitiveBehaviour(_In_ int behaviour);
  [[nodiscard]] int AutoCGetCaseInsensitiveBehaviour();
  void AutoCSetMulti(_In_ int multi);
  [[nodiscard]] int AutoCGetMulti();
  void AutoCSetOrder(_In_ int order);
  [[nodiscard]] int AutoCGetOrder();
  void Allocate(_In_ Sci_Position bytes);
  [[nodiscard]] Sci_Position TargetAsUTF8(_Inout_ char* s);
  void SetLengthForEncode(_In_ Sci_Position bytes);
  [[nodiscard]] Sci_Position EncodedFromUTF8(_In_ const char* utf8, _Inout_ char* encoded);
  [[nodiscard]] Sci_Position FindColumn(_In_ intptr_t line, _In_ Sci_Position column);
  [[nodiscard]] int GetCaretSticky();
  void SetCaretSticky(_In_ int useCaretStickyBehaviour);
  void ToggleCaretSticky();
  void SetPasteConvertEndings(_In_ BOOL convert);
  [[nodiscard]] BOOL GetPasteConvertEndings();
  void ReplaceRectangular(_In_ Sci_Position length, _In_z_ const char* text);
  void SelectionDuplicate();
  void SetCaretLineBackAlpha(_In_ int alpha);
  [[nodiscard]] int GetCaretLineBackAlpha();
  void SetCaretStyle(_In_ int caretStyle);
  [[nodiscard]] int GetCaretStyle();
  void SetIndicatorCurrent(_In_ int indicator);
  [[nodiscard]] int GetIndicatorCurrent();
  void SetIndicatorValue(_In_ int value);
  [[nodiscard]] int GetIndicatorValue();
  void IndicatorFillRange(_In_ Sci_Position start, _In_ Sci_Position lengthFill);
  void IndicatorClearRange(_In_ Sci_Position start, _In_ Sci_Position lengthClear);
  [[nodiscard]] int IndicatorAllOnFor(_In_ Sci_Position pos);
  [[nodiscard]] int IndicatorValueAt(_In_ int indicator, _In_ Sci_Position pos);
  [[nodiscard]] Sci_Position IndicatorStart(_In_ int indicator, _In_ Sci_Position pos);
  [[nodiscard]] Sci_Position IndicatorEnd(_In_ int indicator, _In_ Sci_Position pos);
  void SetPositionCache(_In_ int size);
  [[nodiscard]] int GetPositionCache();
  void SetLayoutThreads(_In_ int threads);
  [[nodiscard]] int GetLayoutThreads();
  void CopyAllowLine();
  [[nodiscard]] const char* GetCharacterPointer();
  [[nodiscard]] void* GetRangePointer(_In_ Sci_Position start, _In_ Sci_Position lengthRange);
  [[nodiscard]] Sci_Position GetGapPosition();
  void IndicSetAlpha(_In_ int indicator, _In_ int alpha);
  [[nodiscard]] int IndicGetAlpha(_In_ int indicator);
  void IndicSetOutlineAlpha(_In_ int indicator, _In_ int alpha);
  [[nodiscard]] int IndicGetOutlineAlpha(_In_ int indicator);
  void SetExtraAscent(_In_ int extraAscent);
  [[nodiscard]] int GetExtraAscent();
  void SetExtraDescent(_In_ int extraDescent);
  [[nodiscard]] int GetExtraDescent();
  [[nodiscard]] int MarkerSymbolDefined(_In_ int markerNumber);
  void MarginSetText(_In_ intptr_t line, _In_z_ const char* text);
  int MarginGetText(_In_ intptr_t line, _Inout_opt_z_ char* text);
  void MarginSetStyle(_In_ intptr_t line, _In_ int style);
  [[nodiscard]] int MarginGetStyle(_In_ intptr_t line);
  void MarginSetStyles(_In_ intptr_t line, _In_z_ const char* styles);
  int MarginGetStyles(_In_ intptr_t line, _Inout_opt_z_ char* styles);
  void MarginTextClearAll();
  void MarginSetStyleOffset(_In_ int style);
  [[nodiscard]] int MarginGetStyleOffset();
  void SetMarginOptions(_In_ int marginOptions);
  [[nodiscard]] int GetMarginOptions();
  void AnnotationSetText(_In_ intptr_t line, _In_z_ const char* text);
  int AnnotationGetText(_In_ intptr_t line, _Inout_opt_z_ char* text);
  void AnnotationSetStyle(_In_ intptr_t line, _In_ int style);
  [[nodiscard]] int AnnotationGetStyle(_In_ intptr_t line);
  void AnnotationSetStyles(_In_ intptr_t line, _In_z_ const char* styles);
  int AnnotationGetStyles(_In_ intptr_t line, _Inout_opt_z_ char* styles);
  [[nodiscard]] int AnnotationGetLines(_In_ intptr_t line);
  void AnnotationClearAll();
  void AnnotationSetVisible(_In_ int visible);
  [[nodiscard]] int AnnotationGetVisible();
  void AnnotationSetStyleOffset(_In_ int style);
  [[nodiscard]] int AnnotationGetStyleOffset();
  void ReleaseAllExtendedStyles();
  int AllocateExtendedStyles(_In_ int numberStyles);
  void AddUndoAction(_In_ int token, _In_ int flags);
  [[nodiscard]] Sci_Position CharPositionFromPoint(_In_ int x, _In_ int y);
  [[nodiscard]] Sci_Position CharPositionFromPointClose(_In_ int x, _In_ int y);
  void SetMouseSelectionRectangularSwitch(_In_ BOOL mouseSelectionRectangularSwitch);
  [[nodiscard]] BOOL GetMouseSelectionRectangularSwitch();
  void SetMultipleSelection(_In_ BOOL multipleSelection);
  [[nodiscard]] BOOL GetMultipleSelection();
  void SetAdditionalSelectionTyping(_In_ BOOL additionalSelectionTyping);
  [[nodiscard]] BOOL GetAdditionalSelectionTyping();
  void SetAdditionalCaretsBlink(_In_ BOOL additionalCaretsBlink);
  [[nodiscard]] BOOL GetAdditionalCaretsBlink();
  void SetAdditionalCaretsVisible(_In_ BOOL additionalCaretsVisible);
  [[nodiscard]] BOOL GetAdditionalCaretsVisible();
  [[nodiscard]] int GetSelections();
  [[nodiscard]] BOOL GetSelectionEmpty();
  void ClearSelections();
  void SetSelection(_In_ Sci_Position caret, _In_ Sci_Position anchor);
  void AddSelection(_In_ Sci_Position caret, _In_ Sci_Position anchor);
  void DropSelectionN(_In_ int selection);
  void SetMainSelection(_In_ int selection);
  [[nodiscard]] int GetMainSelection();
  void SetSelectionNCaret(_In_ int selection, _In_ Sci_Position caret);
  [[nodiscard]] Sci_Position GetSelectionNCaret(_In_ int selection);
  void SetSelectionNAnchor(_In_ int selection, _In_ Sci_Position anchor);
  [[nodiscard]] Sci_Position GetSelectionNAnchor(_In_ int selection);
  void SetSelectionNCaretVirtualSpace(_In_ int selection, _In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetSelectionNCaretVirtualSpace(_In_ int selection);
  void SetSelectionNAnchorVirtualSpace(_In_ int selection, _In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetSelectionNAnchorVirtualSpace(_In_ int selection);
  void SetSelectionNStart(_In_ int selection, _In_ Sci_Position anchor);
  [[nodiscard]] Sci_Position GetSelectionNStart(_In_ int selection);
  [[nodiscard]] Sci_Position GetSelectionNStartVirtualSpace(_In_ int selection);
  void SetSelectionNEnd(_In_ int selection, _In_ Sci_Position caret);
  [[nodiscard]] Sci_Position GetSelectionNEndVirtualSpace(_In_ int selection);
  [[nodiscard]] Sci_Position GetSelectionNEnd(_In_ int selection);
  void SetRectangularSelectionCaret(_In_ Sci_Position caret);
  [[nodiscard]] Sci_Position GetRectangularSelectionCaret();
  void SetRectangularSelectionAnchor(_In_ Sci_Position anchor);
  [[nodiscard]] Sci_Position GetRectangularSelectionAnchor();
  void SetRectangularSelectionCaretVirtualSpace(_In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetRectangularSelectionCaretVirtualSpace();
  void SetRectangularSelectionAnchorVirtualSpace(_In_ Sci_Position space);
  [[nodiscard]] Sci_Position GetRectangularSelectionAnchorVirtualSpace();
  void SetVirtualSpaceOptions(_In_ int virtualSpaceOptions);
  [[nodiscard]] int GetVirtualSpaceOptions();
  void SetRectangularSelectionModifier(_In_ int modifier);
  [[nodiscard]] int GetRectangularSelectionModifier();
  void SetAdditionalSelFore(_In_ COLORREF fore);
  void SetAdditionalSelBack(_In_ COLORREF back);
  void SetAdditionalSelAlpha(_In_ int alpha);
  [[nodiscard]] int GetAdditionalSelAlpha();
  void SetAdditionalCaretFore(_In_ COLORREF fore);
  [[nodiscard]] COLORREF GetAdditionalCaretFore();
  void RotateSelection();
  void SwapMainAnchorCaret();
  void MultipleSelectAddNext();
  void MultipleSelectAddEach();
  int ChangeLexerState(_In_ Sci_Position start, _In_ Sci_Position end);
  [[nodiscard]] intptr_t ContractedFoldNext(_In_ intptr_t lineStart);
  void VerticalCentreCaret();
  void MoveSelectedLinesUp();
  void MoveSelectedLinesDown();
  void SetIdentifier(_In_ int identifier);
  [[nodiscard]] int GetIdentifier();
  void RGBAImageSetWidth(_In_ int width);
  void RGBAImageSetHeight(_In_ int height);
  void RGBAImageSetScale(_In_ int scalePercent);
  void MarkerDefineRGBAImage(_In_ int markerNumber, _In_ const char* pixels);
  void RegisterRGBAImage(_In_ int type, _In_ const char* pixels);
  void ScrollToStart();
  void ScrollToEnd();
  void SetTechnology(_In_ int technology);
  [[nodiscard]] int GetTechnology();
  [[nodiscard]] void* CreateLoader(_In_ Sci_Position bytes, _In_ int documentOptions);
  void FindIndicatorShow(_In_ Sci_Position start, _In_ Sci_Position end);
  void FindIndicatorFlash(_In_ Sci_Position start, _In_ Sci_Position end);
  void FindIndicatorHide();
  void VCHomeDisplay();
  void VCHomeDisplayExtend();
  [[nodiscard]] BOOL GetCaretLineVisibleAlways();
  void SetCaretLineVisibleAlways(_In_ BOOL alwaysVisible);
  void SetLineEndTypesAllowed(_In_ int lineEndBitSet);
  [[nodiscard]] int GetLineEndTypesAllowed();
  [[nodiscard]] int GetLineEndTypesActive();
  void SetRepresentation(_In_z_ const char* encodedCharacter, _In_z_ const char* representation);
  int GetRepresentation(_In_z_ const char* encodedCharacter, _Inout_z_ char* representation);
  void ClearRepresentation(_In_z_ const char* encodedCharacter);
  void ClearAllRepresentations();
  void SetRepresentationAppearance(_In_z_ const char* encodedCharacter, _In_ int appearance);
  [[nodiscard]] int GetRepresentationAppearance(_In_z_ const char* encodedCharacter);
  void SetRepresentationColour(_In_z_ const char* encodedCharacter, _In_ int colour);
  [[nodiscard]] int GetRepresentationColour(_In_z_ const char* encodedCharacter);
  void EOLAnnotationSetText(_In_ intptr_t line, _In_z_ const char* text);
  int EOLAnnotationGetText(_In_ intptr_t line, _Inout_opt_z_ char* text);
  void EOLAnnotationSetStyle(_In_ intptr_t line, _In_ int style);
  [[nodiscard]] int EOLAnnotationGetStyle(_In_ intptr_t line);
  void EOLAnnotationClearAll();
  void EOLAnnotationSetVisible(_In_ int visible);
  [[nodiscard]] int EOLAnnotationGetVisible();
  void EOLAnnotationSetStyleOffset(_In_ int style);
  [[nodiscard]] int EOLAnnotationGetStyleOffset();
  [[nodiscard]] BOOL SupportsFeature(_In_ int feature);
  [[nodiscard]] int GetLineCharacterIndex();
  void AllocateLineCharacterIndex(_In_ int lineCharacterIndex);
  void ReleaseLineCharacterIndex(_In_ int lineCharacterIndex);
  [[nodiscard]] intptr_t LineFromIndexPosition(_In_ Sci_Position pos, _In_ int lineCharacterIndex);
  [[nodiscard]] Sci_Position IndexPositionFromLine(_In_ intptr_t line, _In_ int lineCharacterIndex);
  void StartRecord();
  void StopRecord();
  [[nodiscard]] int GetLexer();
  void Colourise(_In_ Sci_Position start, _In_ Sci_Position end);
  void SetScintillaProperty(_In_z_ const char* key, _In_z_ const char* value);
  void SetKeyWords(_In_ int keyWordSet, _In_z_ const char* keyWords);
  int GetScintillaProperty(_In_z_ const char* key, _Inout_opt_z_ char* value);
  int GetPropertyExpanded(_In_z_ const char* key, _Inout_opt_z_ char* value);
  [[nodiscard]] int GetPropertyInt(_In_z_ const char* key, _In_ int defaultValue);
  int GetLexerLanguage(_Inout_opt_z_ char* language);
  [[nodiscard]] void* PrivateLexerCall(_In_ int operation, _In_opt_ void* pointer);
  int PropertyNames(_Inout_opt_z_ char* names);
  [[nodiscard]] int PropertyType(_In_z_ const char* name);
  int DescribeProperty(_In_z_ const char* name, _Inout_opt_z_ char* description);
  int DescribeKeyWordSets(_Inout_opt_z_ char* descriptions);
  [[nodiscard]] int GetLineEndTypesSupported();
  int AllocateSubStyles(_In_ int styleBase, _In_ int numberStyles);
  [[nodiscard]] int GetSubStylesStart(_In_ int styleBase);
  [[nodiscard]] int GetSubStylesLength(_In_ int styleBase);
  [[nodiscard]] int GetStyleFromSubStyle(_In_ int subStyle);
  [[nodiscard]] int GetPrimaryStyleFromStyle(_In_ int style);
  void FreeSubStyles();
  void SetIdentifiers(_In_ int style, _In_z_ const char* identifiers);
  [[nodiscard]] int DistanceToSecondaryStyles();
  int GetSubStyleBases(_Inout_opt_z_ char* styles);
  [[nodiscard]] int GetNamedStyles();
  int NameOfStyle(_In_ int style, _Inout_opt_z_ char* name);
  int TagsOfStyle(_In_ int style, _Inout_opt_z_ char* tags);
  int DescriptionOfStyle(_In_ int style, _Inout_opt_z_ char* description);
  void SetILexer(_In_ void* ilexer);
  [[nodiscard]] int GetBidirectional();
  void SetBidirectional(_In_ int bidirectional);

protected:
  DECLARE_DYNAMIC(CScintillaCtrl)

//Member variables
  BOOL m_bCallDirect;
  SciFnDirect m_DirectFunction;
  SciFnDirectStatus m_DirectStatusFunction;
  sptr_t m_DirectPointer;
};


#endif //#ifndef __SCINTILLACTRL_H__
